getwd()
setwd("C:/Users/User/Documents/GIT/BC/AsociacnePravidla")
spojeneTabulky = readRDS("FinalneBcTriedenie.rda")
library(arules)
library(arulesViz)
selektovaneTransakcie = read.transactions("modifikovaneTrans.csv",format="single",cols=c(1,2),sep=",")
summary(itemFrequency(selektovaneTransakcie))
pravidla <- apriori(selektovaneTransakcie,parameter=list(support=0.0047,confidence=.2))
inspect(pravidla)
plot(pravidla, measure=c("support","lift"), shading="confidence")
plot(pravidla, method = "two-key plot")
plot(pravidla, method="graph")
plot(pravidla, method="grouped")
plot(pravidla, method="paracoord", control=list(reorder=TRUE))

